config/routes.rb
Rails.application.routes.draw do
  devise_for :professionals, controllers: {
    sessions: 'professionals/sessions',
    registrations: 'professionals/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  authenticated :user do
    root to: 'home#dashboard', as: :authenticated_user_root
  end

  authenticated :professional do
    root to: 'home#dashboard', as: :authenticated_professional_root
  end

  root to: 'home#index'
  
  resources :projects, only: [:index, :show, :new, :create, :edit, :update] do
    get '/search', to: 'projects#search', on: :collection
    get '/my', to: 'projects#my_projects', on: :collection

    resources :proposals, only: [:new, :create]
  end

  resources :proposals, only: [:edit, :update, :destroy] do
    get '/cancel', to: 'proposals#cancel'
    get '/refuse', to: 'proposals#refuse'
    put '/approve', to: 'proposals#approve'
  end

  resources :professionals, only: [:show]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def dashboard; end
end

app/views/home/dashboard.html.erb
<% if user_signed_in? %>
  <h2>Meus projetos</h2>
  <% if current_user.projects.empty? %>
    <p>Você ainda não tem projetos</p>
    <%= link_to 'Crie um projeto', new_project_path, class: 'btn btn-primary' %>
  <% else %>
    <%= render current_user.projects %>
  <% end %>
<% end %>

<% if professional_signed_in? %>
  <h2>Meu perfil</h2>

  <div class="card">
    <div class="card-body">

      <div class="row">
        <div class="col-sm-2">
          <% if current_professional.profile_picture_url %>
          <%= tag.img id: "profile-picture", alt: current_professional.name,
          src: current_professional.profile_picture_url, width: '100', height: '150' %>
          <% end %>
        </div>

        <div class="col-sm">
          <p>Nome social: <%= current_professional.name %></p>
          <p>Nome completo: <%= current_professional.full_name %></p>
          <p>Data de nascimento: <%= I18n.l current_professional.birth_date %></p>
          <p>Descrição: <br> <%= current_professional.description %></p>
        </div>
      </div>

      <hr>
      <div class="row">
        <p>Formação: <br> <%= current_professional.education %></p>
        <p>Experiência: <br> <%= current_professional.experience %></p>
        <p>Habilidades: <%= current_professional.abilities %></p>
      </div>

    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="px-4 py-5 my-5 text-center">
  <h1 class="display-5 fw-bold">Freelancer finder</h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">
      O projeto consiste em criar uma plataforma Web que reúna em torno de projetos a serem executados pessoas interessadas em contratar um freelancer com profissionais de tecnologia.
    </p>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
      <%= link_to 'Contratar freelancers', new_user_registration_path, 
        class: "btn btn-primary btn-lg px-4 gap-3" %>
      <%= link_to 'Encontrar projetos', new_professional_registration_path, 
        class: "btn btn-outline-secondary btn-lg px-4" %>
    </div>
  </div>
</div>