config/routes.rb
Rails.application.routes.draw do
  devise_for :professionals, controllers: {
    sessions: 'professionals/sessions',
    registrations: 'professionals/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  authenticated :user do
    root to: 'home#dashboard', as: :authenticated_user_root
  end

  authenticated :professional do
    root to: 'home#dashboard', as: :authenticated_professional_root
  end

  root to: 'home#index'
  
  resources :projects, only: [:index, :show, :new, :create, :edit, :update] do
    get '/search', to: 'projects#search', on: :collection
    get '/my', to: 'projects#my_projects', on: :collection

    resources :proposals, only: [:new, :create]
  end

  resources :proposals, only: [:edit, :update, :destroy] do
    get '/cancel', to: 'proposals#cancel'
    get '/refuse', to: 'proposals#refuse'
    put '/approve', to: 'proposals#approve'
  end

  resources :professionals, only: [:show]
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id',
                       inverse_of: 'projects'
  has_many :proposals, dependent: :destroy

  validates :title, :description, :desired_abilities, :value_per_hour,
            :due_date, presence: true

  # TODO: validar data após hoje
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update]
  before_action :authenticate_professional!, only: %i[index search my_projects]
  before_action :should_authenticate!, only: :show

  def index
    @projects = Project.all
  end

  def search
    query = ActiveRecord::Base.sanitize_sql_like(params[:query])
    @projects = Project.where('title LIKE :query OR description LIKE :query',
                              query: "%#{query}%")

    render :index
  end

  def show
    if professional_signed_in?
      find_project_and_proposals_for_professional
    elsif user_signed_in?
      find_project_and_proposals_for_user
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.creator = current_user

    if @project.save
      flash[:notice] = 'Projeto salvo com sucesso'
      redirect_to @project
    else
      render :new
    end
  end

  def edit
    @project = current_user.projects.find(params[:id])
  end

  def update
    @project = current_user.projects.find(params[:id])

    if @project.update(project_params)
      flash[:notice] = 'Projeto atualizado com sucesso'
      redirect_to @project
    else
      render :edit
    end
  end

  def my_projects
    @proposals = current_professional.not_canceled_proposals
                                     .order(updated_at: :desc)
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :desired_abilities,
                                    :value_per_hour, :due_date, :remote)
  end

  def find_project_and_proposals_for_professional
    @project = Project.find(params[:id])
    @proposal = current_professional.not_canceled_proposals
                                    .find_by(project_id: params[:id])
  end

  def find_project_and_proposals_for_user
    @project = current_user.projects.find(params[:id])
    @proposals = @project.proposals.where.not(
      status: %i[canceled_pending refused]
    )
  end
end

app/views/projects/_form.html.erb
<%= form_with model: @project do |f| %>
  <div class="form-floating my-3">
    <%= f.text_field :title, class: "form-control", placeholder: "Título" %>
    <%= f.label :title %>
    <% @project.errors.full_messages_for(:title).each do |message| %>
      <div class="invalid-feedback">
        <%= message %>
      </div>
    <% end %>
  </div>

  <div class="form-floating my-3">
    <%= f.text_area :description, class: "form-control", placeholder: "Meu novo projeto" %>
    <%= f.label :description %>
    <% @project.errors.full_messages_for(:description).each do |message| %>
      <div class="invalid-feedback">
        <%= message %>
      </div>
    <% end %>
  </div>

  <div class="form-floating my-3">
    <%= f.text_area :desired_abilities, class: "form-control", placeholder: "UX, design, etc..." %>
    <%= f.label :desired_abilities %>
    <% @project.errors.full_messages_for(:desired_abilities).each do |message| %>
      <div class="invalid-feedback">
        <%= message %>
      </div>
    <% end %>
  </div>

  <div class="form-floating my-3">
    <%= f.number_field :value_per_hour, { step: 0.01, class: "form-control", placeholder: "Informe um valor" } %>
    <%= f.label :value_per_hour %>
    <% @project.errors.full_messages_for(:value_per_hour).each do |message| %>
      <div class="invalid-feedback">
        <%= message %>
      </div>
    <% end %>
  </div>

  <div class="form-floating my-3">
    <%= f.date_field :due_date, class: "form-control", placeholder: "Informe uma data" %>
    <%= f.label :due_date %>
    <% @project.errors.full_messages_for(:due_date).each do |message| %>
      <div class="invalid-feedback">
        <%= message %>
      </div>
    <% end %>
  </div>

  <div>
    <%= f.check_box :remote %> 
    <%= f.label :remote %>
  </div>

  <div class="actions my-3">
    <%= f.submit 'Enviar', class: "w-100 btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div class="card col-lg-8">
  <div class="card-body row">
    <div class="col-md-8">
      <h5 class="card-title">
        Título: <%= link_to project.title, project_path(project) %>
      </h5>

      <p class="card-text">Descrição: <%= project.description %></p>
      <p>Habilidades desejadas: <%= project.desired_abilities %></p>
      <p>Criado por: <%= project.creator.name %></p>
    </div>

    <div class="col">
      <p>Valor por hora: <%= number_to_currency project.value_per_hour %></p>
      <p>Data limite: <%= I18n.l project.due_date %></p>
      <p>Trabalho <%= project.remote? ? "remoto" : "presencial" %></p>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<main class="form-signin text-center">
  <h1 class="h3 mb-3 fw-normal">Editar projeto</h1>

  <%= render 'form' %>
</main>

app/views/projects/index.html.erb
<h1>Projetos disponíveis</h1>
<br>

<%= form_with url: '/projects/search', method: :get,
  class: 'd-flex flex-column align-items-start flex-sm-row align-items-sm-center' do |form| %>
  <%= form.label :query, 'Buscar por:' %>
  <%= form.text_field :query, { value: params[:query] || '',
    class: 'form-control mx-sm-2', placeholder: 'Título ou descrição...',
    style: 'width: 300px;' } %>
  <%= form.submit 'Buscar', class: 'btn btn-primary mt-2 mt-sm-0' %>
<% end %>

<br>
<div>
  <% if @projects.empty? %>
    <h5>Nenhum projeto encontrado</h5>
  <% else %>
    <%= render @projects %>
  <% end %>
</div>

app/views/projects/my_projects.html.erb
<% @proposal && @proposal.errors.full_messages.each do |message|  %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= message %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<div>
  <div>
    <h2>Minhas propostas</h2>
    <div>
      <% if @proposals.empty? %>
        Você não fez propostas ainda
      <% else %>
        <%= render @proposals %>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<main class="form-signin text-center">
  <h1 class="h3 mb-3 fw-normal">Novo projeto</h1>

  <%= render 'form' %>
</main>

app/views/projects/show.html.erb
<%= render @project %>
<br>

<% if user_signed_in? %>
  <%= link_to 'Editar', edit_project_path(@project), class: 'btn btn-primary' %>
  <br>
  <br>
  <h2>Propostas</h2>
  <% if @proposals.any? %>
    <div>
      <%= render @proposals %>
    </div>
  <% else %>
    <p>Esse projeto ainda não recebeu propostas</p>
  <% end %>

<% elsif professional_signed_in? %>
  <% if @proposal %>
    <h2>Sua proposta</h2>
    <%= render @proposal %>
  <% else %>
    <%= link_to 'Fazer proposta', new_project_proposal_path(@project),
    class: 'btn btn-primary' %>
  <% end %>

<% end %>