config/routes.rb
Rails.application.routes.draw do
  devise_for :professionals, controllers: {
    sessions: 'professionals/sessions',
    registrations: 'professionals/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  authenticated :user do
    root to: 'home#dashboard', as: :authenticated_user_root
  end

  authenticated :professional do
    root to: 'home#dashboard', as: :authenticated_professional_root
  end

  root to: 'home#index'
  
  resources :projects, only: [:index, :show, :new, :create, :edit, :update] do
    get '/search', to: 'projects#search', on: :collection
    get '/my', to: 'projects#my_projects', on: :collection

    resources :proposals, only: [:new, :create]
  end

  resources :proposals, only: [:edit, :update, :destroy] do
    get '/cancel', to: 'proposals#cancel'
    get '/refuse', to: 'proposals#refuse'
    put '/approve', to: 'proposals#approve'
  end

  resources :professionals, only: [:show]
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :project
  belongs_to :professional
  has_one :proposal_cancelation, dependent: :destroy
  has_one :proposal_refusal, dependent: :destroy

  enum status: {
    pending: 0,
    analyzing: 10,
    approved: 20,
    canceled_pending: 30,
    canceled_approved: 40,
    refused: 50
  }

  validates :message, :value_per_hour, :hours_per_week, :finish_date,
            presence: true

  validates :value_per_hour, numericality: true

  validates :hours_per_week,
            numericality: { only_integer: true, greater_than: 0 }

  before_save :approved_date, if: -> { approved? && approved_at.nil? }

  def cancel!(cancel_reason = '')
    if pending?
      canceled_pending!
    elsif can_cancel_at_current_date?
      canceled_approved!
      self.proposal_cancelation = ProposalCancelation
                                  .new(cancel_reason: cancel_reason)
    else
      return false
    end

    save
  end

  def can_cancel_at_current_date?
    return false if canceled_pending? || canceled_approved? || refused?

    return true if approved? && Date.current < (approved_at + 3.days).to_date

    errors.add(:approved_at, "#{I18n.l approved_at.to_date}. "\
                             'Não é possível cancelar a proposta após 3 dias.')

    false
  end

  def refuse!(refuse_reason = '')
    return false if canceled_pending? || canceled_approved? || refused?

    refused!
    self.proposal_refusal = ProposalRefusal
                            .new(refuse_reason: refuse_reason)

    save
  end

  def approve!
    approved! unless canceled_pending? || canceled_approved? || refused?
  end

  private

  def approved_date
    self.approved_at = Date.current
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :should_authenticate!, only: :destroy
  before_action :authenticate_professional!, only: %i[new create edit update
                                                      cancel]
  before_action :authenticate_user!, only: %i[refuse approve]
  before_action :verify_duplicated_or_refused_proposal, only: %i[new create]
  before_action :verify_refused_proposal_modification,
                only: %i[edit update cancel destroy],
                if: :professional_signed_in?

  def new
    @project = Project.find(params[:project_id])
    @proposal = Proposal.new
  end

  def create
    @project = Project.find(params[:project_id])

    @proposal = Proposal.new(
      **proposal_params, project: @project, professional: current_professional
    )

    if @proposal.save
      redirect_to project_path(@project.id),
                  notice: 'Proposta criada com sucesso'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @proposal.approved?
      flash[:alert] = 'Não é possível alterar as informações de '\
                      'uma proposta aprovada'
      redirect_to project_path(@proposal.project)
    elsif @proposal.update(proposal_params)
      flash[:notice] = 'Proposta atualizada com sucesso'
      redirect_to my_projects_path
    else
      render :edit
    end
  end

  def cancel
    if @proposal.pending?
      @proposal.cancel!
      redirect_to my_projects_path, notice: 'Proposta cancelada com sucesso'
    elsif !@proposal.can_cancel_at_current_date?
      @proposals = current_professional.not_canceled_proposals
                                       .order(:updated_at)
      render 'projects/my_projects'
    end
  end

  def refuse
    @proposal = Proposal.find_by!(id: params[:proposal_id],
                                  project: [current_user.projects])
  end

  def approve
    proposal = Proposal.find_by!(id: params[:proposal_id],
                                 project: [current_user.projects])
    if proposal.approve!
      flash[:notice] = 'Proposta aprovada com sucesso. Agora você pode '\
                       "trocar mensagens com #{proposal.professional.name}"
    else
      flash[:alert] = 'Não foi possível aprovar a proposta'
    end

    redirect_to project_path(proposal.project)
  end

  def destroy
    if professional_signed_in?
      professional_cancel_proposal
    elsif user_signed_in?
      user_refuse_proposal
    end
  end

  private

  def proposal_params
    params.require(:proposal).permit(:message, :value_per_hour, :hours_per_week,
                                     :finish_date)
  end

  def cancel_reason_params
    params[:proposal][:cancel_reason] || ''
  rescue StandardError
    ''
  end

  def professional_cancel_proposal
    if @proposal.cancel!(cancel_reason_params)
      flash[:notice] = 'Proposta cancelada com sucesso'
    else
      @proposals = current_professional.not_canceled_proposals
                                       .order(:updated_at)
      render 'projects/my_projects' and return
    end

    redirect_to my_projects_path
  end

  def user_refuse_proposal
    @proposal = Proposal.find_by!(id: params[:id],
                                  project: [current_user.projects])

    if @proposal.refuse!(params[:proposal][:refuse_reason])
      flash[:notice] = 'Proposta recusada com sucesso'
    else
      flash[:alert] = 'Não é possível recusar essa proposta'
    end

    redirect_to project_path(@proposal.project)
  end
end

app/views/proposals/_proposal.html.erb
<div
  class="<%= "card col-lg-8 border-#{proposal.status}" %>"
  id=<%= "proposal-#{proposal.id}" %>
>
  <div class="card-body row">
    <div class="col-md-8">
      <% unless user_signed_in? && request.path.include?('/projects') %>
        <h5 class="card-title">
          Projeto: <%= link_to proposal.project.title, project_path(proposal.project) %>
        </h5>
      <% end %>
      <p>Mensagem: <br><%= proposal.message %></p>

      <% if user_signed_in? %>
        <p>
          Enviado por: <%= link_to "#{proposal.professional.name}",
          professional_path(proposal.professional) %>
        </p>
      <% end %>

      <% if proposal.canceled_approved? %>
        <p>
          Motivo de cancelamento: <br>
          <%= proposal.proposal_cancelation.cancel_reason %>
        </p>
      <% elsif proposal.refused? %>
        <p>
          Motivo de recusa: <br>
          <%= proposal.proposal_refusal.refuse_reason %>
        </p>
      <% end %>
    </div>

    <div class="col">
      <p>Status: <%= Proposal.human_enum_name(:status, proposal.status) %></p>
      <% if proposal.approved?%>
        <p>Aprovada em <%= I18n.l proposal.approved_at %></p>
      <% end %>
      <p>Valor por hora: <%= number_to_currency proposal.value_per_hour %></p>
      <p>Horas disponíveis por semana: <%= proposal.hours_per_week %></p>
      <p>Expectativa de conclusão: <%= I18n.l proposal.finish_date %></p>
    </div>

    <% if professional_signed_in? && !proposal.refused? %>
      <div>
        <%= link_to 'Editar', edit_proposal_path(proposal), class: 'btn btn-primary' %> 

        <% if proposal.pending? %>
          <%= link_to 'Cancelar proposta', proposal_path(proposal),
            class: 'btn btn-danger', method: :delete,
            data: { confirm: 'Cancelar proposta?' } %>
        <% elsif proposal.approved? %>
          <%= link_to 'Cancelar proposta', proposal_cancel_path(proposal),
            class: 'btn btn-danger' %>
        <% end %>
      </div>
    <% end %>

    <% if user_signed_in? && !proposal.canceled_approved? %>
      <div>
        <%= link_to 'Aprovar', proposal_approve_path(proposal),
          class: 'btn btn-primary mr-2', method: :put %>
        <%= link_to 'Recusar', proposal_refuse_path(proposal), class: 'btn btn-danger' %>
      </div>
    <% end %>
  </div>
</div>

app/views/proposals/cancel.html.erb
<main class="form-signin text-center">
  <%= form_with model: @proposal, method: :delete do |f| %>
    <div>
      <%= f.label :cancel_reason, 'Informe por que quer cancelar a proposta:',
        class: 'h4 mb-3 fw-normal' %>
      <br>
      <%= f.text_area :cancel_reason, class: 'form-control', rows: '5' %>
    </div>
    
    <br>
    <div class="actions">
      <%= f.submit 'Cancelar proposta', class: "w-100 btn btn-lg btn-danger" %>
    </div>
  <% end %>
</main>

app/views/proposals/edit.html.erb
<main class="form-signin text-center">
  <%= form_with model: @proposal do |f| %>

    <h2 class="h3 mb-3 fw-normal">Editar proposta em <%= @proposal.project.title %></h2>

    <div class="form-floating my-3">
      <%= f.text_area :message, autofocus: true, class: 'form-control', placeholder: 'Conte por quê está se candidatando, experiência, etc...' %>
      <%= f.label :message %>
      <% @proposal.errors.full_messages_for(:message).each do |message| %>
        <div class="invalid-feedback">
          <%= message %>
        </div>
      <% end %>
    </div>

    <div class="form-floating my-3">
      <%= f.number_field :value_per_hour, class: 'form-control', placeholder: 'Valor por hora', step: 0.01 %>
      <%= f.label :value_per_hour %>
      <% @proposal.errors.full_messages_for(:value_per_hour).each do |message| %>
        <div class="invalid-feedback">
          <%= message %>
        </div>
      <% end %>
    </div>

    <div class="form-floating my-3">
      <%= f.number_field :hours_per_week, class: 'form-control', placeholder: 'Horas por semana' %>
      <%= f.label :hours_per_week %>
      <% @proposal.errors.full_messages_for(:hours_per_week).each do |message| %>
        <div class="invalid-feedback">
          <%= message %>
        </div>
      <% end %>
    </div>

    <div class="form-floating my-3">
      <%= f.date_field :finish_date, class: 'form-control', placeholder: 'Expectativa de conclusão' %>
      <%= f.label :finish_date %>
      <% @proposal.errors.full_messages_for(:finish_date).each do |message| %>
        <div class="invalid-feedback">
          <%= message %>
        </div>
      <% end %>
    </div>

    <br>
    <div class="actions">
      <%= f.submit class: "w-100 btn btn-lg btn-primary" %>
    </div>
  <% end %>
</main>

app/views/proposals/new.html.erb
<main class="form-signin text-center">
  <%= form_with model: [@project, @proposal] do |f| %>

    <h2 class="h3 mb-3 fw-normal">Nova proposta em <%= @project.title %></h2>

    <div class="form-floating my-3">
      <%= f.text_area :message, autofocus: true, class: "form-control",
        placeholder: "Conte por quê está se candidatando, experiência, etc..." %>
      <%= f.label :message %>
      <% @proposal.errors.full_messages_for(:message).each do |message| %>
        <div class="invalid-feedback">
          <%= message %>
        </div>
      <% end %>
    </div>

    <div class="form-floating my-3">
      <%= f.number_field :value_per_hour, class: "form-control", step: 0.01,
        placeholder: "Valor por hora" %>
      <%= f.label :value_per_hour %>
      <% @proposal.errors.full_messages_for(:value_per_hour).each do |message| %>
        <div class="invalid-feedback">
          <%= message %>
        </div>
      <% end %>
    </div>

    <div class="form-floating my-3">
      <%= f.number_field :hours_per_week, class: "form-control",
        placeholder: "Horas por semana" %>
      <%= f.label :hours_per_week %>
      <% @proposal.errors.full_messages_for(:hours_per_week).each do |message| %>
        <div class="invalid-feedback">
          <%= message %>
        </div>
      <% end %>
    </div>

    <div class="form-floating my-3">
      <%= f.date_field :finish_date, class: "form-control",
        placeholder: "Expectativa de conclusão" %>
      <%= f.label :finish_date %>
      <% @proposal.errors.full_messages_for(:finish_date).each do |message| %>
        <div class="invalid-feedback">
          <%= message %>
        </div>
      <% end %>
    </div>

    <br>
    <div class="actions">
      <%= f.submit class: "w-100 btn btn-lg btn-primary" %>
    </div>
  <% end %>
</main>

app/views/proposals/refuse.html.erb
<main class="form-signin text-center">
  <%= form_with model: @proposal, method: :delete do |f| %>
    <div>
      <%= f.label :refuse_reason, 'Informe por que quer recusar a proposta:',
        class: 'h4 mb-3 fw-normal' %>
      <br>
      <%= f.text_area :refuse_reason, class: 'form-control', rows: '5' %>
    </div>
    
    <br>
    <div class="actions">
      <small class="text-danger">
        O profissional não poderá criar novas propostas nesse projeto
      </small>
      <%= f.submit 'Recusar proposta', class: "w-100 btn btn-lg btn-danger" %>
    </div>
  <% end %>
</main>