config/routes.rb
Rails.application.routes.draw do
  devise_for :professionals, controllers: {
    sessions: 'professionals/sessions',
    registrations: 'professionals/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  authenticated :user do
    root to: 'home#dashboard', as: :authenticated_user_root
  end

  authenticated :professional do
    root to: 'home#dashboard', as: :authenticated_professional_root
  end

  root to: 'home#index'
  
  resources :projects, only: [:index, :show, :new, :create, :edit, :update] do
    get '/search', to: 'projects#search', on: :collection
    get '/my', to: 'projects#my_projects', on: :collection

    resources :proposals, only: [:new, :create]
  end

  resources :proposals, only: [:edit, :update, :destroy] do
    get '/cancel', to: 'proposals#cancel'
    get '/refuse', to: 'proposals#refuse'
    put '/approve', to: 'proposals#approve'
  end

  resources :professionals, only: [:show]
end

app/views/layouts/_professional_signed_in_links.html.erb
<% # TODO: mudar navbar para partial %>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-primary">
  <div class="container-fluid">
    <%= link_to 'Freelancer Finder', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <%= link_to 'Início', root_path, class: 'nav-link text-light' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Buscar projetos', projects_path, 
            class: 'nav-link text-light' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Meus projetos', my_projects_path, 
            class: 'nav-link text-light' %>
        </li>
      </ul>
      <div class="d-flex">
        <div class="bg-light p-2 me-2 rounded" data-test="username">
          <%= current_professional.name %>
        </div>

        <%= link_to 'Sair', destroy_professional_session_path, method: :delete, 
          class: 'btn btn-outline-light' %>

        <!-- <%= link_to "#{current_professional.name} (Sair)", destroy_user_session_path, method: :delete, class: 'btn btn-light' %> -->
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_user_signed_in_links.html.erb
<% # TODO: mudar navbar para partial %>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-primary">
  <div class="container-fluid">
    <%= link_to 'Freelancer Finder', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <%= link_to 'Início', root_path, class: 'nav-link text-light' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Criar projeto', new_project_path, 
            class: 'nav-link text-light' %>
        </li>
      </ul>
      <div class="d-flex">
        <div class="bg-light p-2 me-2 rounded" data-test="username">
          <%= current_user.name %>
        </div>

        <%= link_to 'Sair', destroy_user_session_path, method: :delete, 
          class: 'btn btn-outline-light' %>

        <!-- <%= link_to "#{current_user.name} (Sair)", destroy_user_session_path, 
          method: :delete, 
          class: 'btn btn-light' %> -->
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freelancer Finder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render 'layouts/user_signed_in_links' %>
    <% elsif professional_signed_in? %>
      <%= render 'layouts/professional_signed_in_links' %>
    <% end %>

    <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= alert %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    
    <div class="mx-2 mx-sm-4 mb-4">
      <%= yield %>
    </div>
  </body>
</html>